- name: Show Drives on the Desktop
  shell: defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

- name: Show External Drives on the Desktop
  shell: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true

- name: Show Removable Media on the Desktop
  shell: defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

- name: Show Hidden Files
  shell: defaults write com.apple.finder AppleShowAllFiles -bool true

- name: Show File Extensions
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: Show the Status Bar in Finder
  shell: defaults write com.apple.finder ShowStatusBar -bool true

- name: Show the Path Bar in Finder
  shell: defaults write com.apple.finder ShowPathbar -bool false
  
- name: Remove recent applications from the dock
  shell: defaults write com.apple.dock show-recents -bool false;
  
- name: Set number of recent applications to show in the dock
  shell: defaults write com.apple.dock show-recent-count -int 3;

- name: Restart Dock
  shell: killall Dock

- name: Restart Finder
  shell: killall Finder
